"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { obterPortaCrmApi } from "@/infraestrutura/obter-porta-crm-api";

const uuid = z.string().uuid();
export async function criarRoteiro(dados: FormData) { const x = z.object({ data: z.string().date(), nomeMotorista: z.string().trim().min(1).max(120) }).parse(Object.fromEntries(dados)); await obterPortaCrmApi().criarRoteiro(x.data, x.nomeMotorista); revalidatePath("/roteiros"); redirect(`/roteiros?data=${x.data}`); }
export async function adicionarParada(dados: FormData) { const x = z.object({ roteiroId: uuid, data: z.string().date(), clienteId: uuid, tipo: z.enum(["Coleta", "Entrega"]), periodo: z.string().trim().min(1).max(80), observacao: z.string().trim().max(500) }).parse(Object.fromEntries(dados)); await obterPortaCrmApi().adicionarParada(x.roteiroId, { clienteId: x.clienteId, tipo: x.tipo, periodo: x.periodo, observacao: x.observacao || null }); revalidatePath("/roteiros"); redirect(`/roteiros?data=${x.data}`); }
export async function editarParada(dados: FormData) { const x = z.object({ roteiroId: uuid, paradaId: uuid, data: z.string().date(), tipo: z.enum(["Coleta", "Entrega"]), periodo: z.string().trim().min(1).max(80), observacao: z.string().trim().max(500) }).parse(Object.fromEntries(dados)); await obterPortaCrmApi().atualizarParada(x.roteiroId, x.paradaId, { tipo: x.tipo, periodo: x.periodo, observacao: x.observacao || null }); revalidatePath("/roteiros"); redirect(`/roteiros?data=${x.data}`); }
export async function removerParada(dados: FormData) { const x = z.object({ roteiroId: uuid, paradaId: uuid, data: z.string().date() }).parse(Object.fromEntries(dados)); await obterPortaCrmApi().removerParada(x.roteiroId, x.paradaId); revalidatePath("/roteiros"); redirect(`/roteiros?data=${x.data}`); }
export async function moverParada(dados: FormData) { const x = z.object({ roteiroId: uuid, data: z.string().date(), paradaId: uuid, direcao: z.enum(["cima", "baixo"]), ordem: z.string() }).parse(Object.fromEntries(dados)); const ids = x.ordem.split(",").filter(Boolean); const i = ids.indexOf(x.paradaId); const destino = x.direcao === "cima" ? i - 1 : i + 1; if (i >= 0 && destino >= 0 && destino < ids.length) [ids[i], ids[destino]] = [ids[destino], ids[i]]; await obterPortaCrmApi().reordenarParadas(x.roteiroId, ids); revalidatePath("/roteiros"); redirect(`/roteiros?data=${x.data}`); }
export async function publicarRoteiro(dados: FormData) { const x = z.object({ roteiroId: uuid, data: z.string().date() }).parse(Object.fromEntries(dados)); await obterPortaCrmApi().publicarRoteiro(x.roteiroId); revalidatePath("/roteiros"); revalidatePath("/meu-roteiro"); redirect(`/roteiros?data=${x.data}&publicado=1`); }
export async function atualizarParada(dados: FormData) { const x = z.object({ paradaId: uuid, acao: z.enum(["iniciar", "concluir"]), data: z.string().date() }).parse(Object.fromEntries(dados)); const api = obterPortaCrmApi(); if (x.acao === "iniciar") await api.iniciarParada(x.paradaId); else await api.concluirParada(x.paradaId); revalidatePath("/meu-roteiro"); redirect(`/meu-roteiro?data=${x.data}`); }
export async function naoRealizarParada(dados: FormData) { const x = z.object({ paradaId: uuid, data: z.string().date(), motivo: z.string().trim().min(3).max(300) }).parse(Object.fromEntries(dados)); await obterPortaCrmApi().naoRealizarParada(x.paradaId, x.motivo); revalidatePath("/meu-roteiro"); redirect(`/meu-roteiro?data=${x.data}`); }
