// <auto-generated />
using System;
using LavaMais.Crm.Modulos.MovimentacoesComerciais.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LavaMais.Crm.Modulos.MovimentacoesComerciais.Infraestrutura.Migrations
{
    [DbContext(typeof(ContextoDeMovimentacoesComerciais))]
    [Migration("20260825194218_AdicionarLinhasDeArtigosEServicos")]
    partial class AdicionarLinhasDeArtigosEServicos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("movimentacoes_comerciais")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LavaMais.Crm.Modulos.MovimentacoesComerciais.Dominio.LinhaDaMovimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtigoDeLavanderiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("artigo_de_lavanderia_id");

                    b.Property<Guid>("MovimentacaoComercialId")
                        .HasColumnType("uuid")
                        .HasColumnName("movimentacao_comercial_id");

                    b.Property<string>("NomeArtigoSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome_artigo_snapshot");

                    b.Property<string>("NomeServicoSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome_servico_snapshot");

                    b.Property<Guid>("OfertaDeServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("oferta_de_servico_id");

                    b.Property<decimal>("PrecoTabelaSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco_tabela_snapshot");

                    b.Property<decimal>("PrecoUnitarioPraticado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco_unitario_praticado");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("ServicoDeLavanderiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("servico_de_lavanderia_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("MovimentacaoComercialId");

                    b.HasIndex("TenantId", "MovimentacaoComercialId", "OfertaDeServicoId")
                        .IsUnique();

                    b.ToTable("linhas_da_movimentacao", "movimentacoes_comerciais");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.MovimentacoesComerciais.Dominio.MovimentacaoComercial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("CodigoExterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_externo");

                    b.Property<DateTimeOffset?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cancelamento");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTimeOffset>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_movimentacao");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("NomeClienteSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_cliente_snapshot");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origem");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("situacao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UsuarioCancelamentoId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario_cancelamento_id");

                    b.Property<string>("UsuarioRegistroId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario_registro_id");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CodigoExterno")
                        .IsUnique()
                        .HasFilter("codigo_externo IS NOT NULL");

                    b.HasIndex("TenantId", "DataMovimentacao");

                    b.HasIndex("TenantId", "ClienteId", "DataMovimentacao");

                    b.ToTable("movimentacoes", "movimentacoes_comerciais");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.MovimentacoesComerciais.Dominio.LinhaDaMovimentacao", b =>
                {
                    b.HasOne("LavaMais.Crm.Modulos.MovimentacoesComerciais.Dominio.MovimentacaoComercial", null)
                        .WithMany("Linhas")
                        .HasForeignKey("MovimentacaoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.MovimentacoesComerciais.Dominio.MovimentacaoComercial", b =>
                {
                    b.Navigation("Linhas");
                });
#pragma warning restore 612, 618
        }
    }
}
