// <auto-generated />
using System;
using LavaMais.Crm.Modulos.AcoesComerciais.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LavaMais.Crm.Modulos.AcoesComerciais.Infraestrutura.Migrations
{
    [DbContext(typeof(ContextoDeAcoesComerciais))]
    partial class ContextoDeAcoesComerciaisModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("acoes_comerciais")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LavaMais.Crm.Modulos.AcoesComerciais.Dominio.AcaoComercial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CriteriosSegmentacaoJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("criterios_segmentacao_json");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTimeOffset?>("DataInicioProcessamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio_processamento");

                    b.Property<DateTimeOffset?>("DataPreparacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_preparacao");

                    b.Property<Guid?>("ItemDeCatalogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_de_catalogo_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeItemSnapshot")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome_item_snapshot");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("objetivo");

                    b.Property<int>("QuantidadeDestinatarios")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_destinatarios");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UsuarioCriacaoId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario_criacao_id");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("VersaoModeloId")
                        .HasColumnType("uuid")
                        .HasColumnName("versao_modelo_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Situacao");

                    b.ToTable("acoes_comerciais", "acoes_comerciais");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.AcoesComerciais.Dominio.DestinatarioDaAcao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcaoComercialId")
                        .HasColumnType("uuid")
                        .HasColumnName("acao_comercial_id");

                    b.Property<string>("ChaveIdempotencia")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("chave_idempotencia");

                    b.Property<string>("ChaveTemplateNotificacaoSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("chave_template_notificacao_snapshot");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("CodigoFalha")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_falha");

                    b.Property<string>("ConteudoPreVisualizacaoSnapshot")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("conteudo_pre_visualizacao_snapshot");

                    b.Property<DateTimeOffset?>("DataResultadoComercial")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_resultado_comercial");

                    b.Property<DateTimeOffset?>("DataUltimaReconciliacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ultima_reconciliacao");

                    b.Property<string>("DestinoSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("destino_snapshot");

                    b.Property<string>("NomeClienteSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_cliente_snapshot");

                    b.Property<string>("NotificacaoExternaId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("notificacao_externa_id");

                    b.Property<string>("PayloadNotificacaoJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_notificacao_json");

                    b.Property<string>("ResultadoComercial")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("resultado_comercial");

                    b.Property<string>("SituacaoEnvio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao_envio");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UsuarioResultadoId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario_resultado_id");

                    b.Property<decimal?>("ValorConvertido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_convertido");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AcaoComercialId");

                    b.HasIndex("TenantId", "AcaoComercialId", "ClienteId")
                        .IsUnique();

                    b.ToTable("destinatarios_da_acao", "acoes_comerciais");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.AcoesComerciais.Dominio.DestinatarioDaAcao", b =>
                {
                    b.HasOne("LavaMais.Crm.Modulos.AcoesComerciais.Dominio.AcaoComercial", null)
                        .WithMany("Destinatarios")
                        .HasForeignKey("AcaoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.AcoesComerciais.Dominio.AcaoComercial", b =>
                {
                    b.Navigation("Destinatarios");
                });
#pragma warning restore 612, 618
        }
    }
}
