// <auto-generated />
using System;
using LavaMais.Crm.Modulos.ModelosDeMensagem.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LavaMais.Crm.Modulos.ModelosDeMensagem.Infraestrutura.Migrations
{
    [DbContext(typeof(ContextoDeModelos))]
    partial class ContextoDeModelosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("comunicacao")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LavaMais.Crm.Modulos.ModelosDeMensagem.Dominio.ModeloDeMensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome_normalizado");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("situacao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("VersaoAtualId")
                        .HasColumnType("uuid")
                        .HasColumnName("versao_atual_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NomeNormalizado")
                        .IsUnique();

                    b.ToTable("modelos_de_mensagem", "comunicacao");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.ModelosDeMensagem.Dominio.VersaoDoModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConteudoPreVisualizacao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("conteudo_pre_visualizacao");

                    b.Property<DateTimeOffset>("DataPublicacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_publicacao");

                    b.Property<Guid>("ModeloId")
                        .HasColumnType("uuid")
                        .HasColumnName("modelo_id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.PrimitiveCollection<string[]>("Variaveis")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("variaveis");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.HasIndex("TenantId", "ModeloId", "Numero")
                        .IsUnique();

                    b.ToTable("versoes_dos_modelos", "comunicacao");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.ModelosDeMensagem.Dominio.VersaoDoModelo", b =>
                {
                    b.HasOne("LavaMais.Crm.Modulos.ModelosDeMensagem.Dominio.ModeloDeMensagem", null)
                        .WithMany("Versoes")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.ModelosDeMensagem.Dominio.ModeloDeMensagem", b =>
                {
                    b.Navigation("Versoes");
                });
#pragma warning restore 612, 618
        }
    }
}
