<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../BlocosDeConstrucao/LavaMais.Crm.BlocosDeConstrucao.csproj" />
    <ProjectReference Include="../Clientes/LavaMais.Crm.Modulos.Clientes.csproj" />
  </ItemGroup>
</Project>
