// <auto-generated />
using System;
using LavaMais.Crm.Modulos.Importacoes.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LavaMais.Crm.Modulos.Importacoes.Infraestrutura.Migrations
{
    [DbContext(typeof(ContextoDeImportacoes))]
    partial class ContextoDeImportacoesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("importacoes")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LavaMais.Crm.Modulos.Importacoes.Dominio.ImportacaoDeClientes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("ConteudoArquivo")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("conteudo_arquivo");

                    b.Property<DateTimeOffset?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_conclusao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_arquivo");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalAtualizadas")
                        .HasColumnType("integer")
                        .HasColumnName("total_atualizadas");

                    b.Property<int>("TotalInseridas")
                        .HasColumnType("integer")
                        .HasColumnName("total_inseridas");

                    b.Property<int>("TotalLinhas")
                        .HasColumnType("integer")
                        .HasColumnName("total_linhas");

                    b.Property<int>("TotalRejeitadas")
                        .HasColumnType("integer")
                        .HasColumnName("total_rejeitadas");

                    b.Property<string>("UsuarioIdentidadeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario_identidade_id");

                    b.Property<long>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("versao");

                    b.HasKey("Id");

                    b.ToTable("importacoes_de_clientes", "importacoes");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.Importacoes.Dominio.LinhaDaImportacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Erro")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("erro");

                    b.Property<Guid>("ImportacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("importacao_id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resultado");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ImportacaoId");

                    b.HasIndex("TenantId", "ImportacaoId", "Numero")
                        .IsUnique();

                    b.ToTable("linhas_da_importacao", "importacoes");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.Importacoes.Dominio.LinhaDaImportacao", b =>
                {
                    b.HasOne("LavaMais.Crm.Modulos.Importacoes.Dominio.ImportacaoDeClientes", null)
                        .WithMany("Linhas")
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.Importacoes.Dominio.ImportacaoDeClientes", b =>
                {
                    b.Navigation("Linhas");
                });
#pragma warning restore 612, 618
        }
    }
}
