"use client";

import { useState, useTransition } from "react";
import { ArrowRight, CircleAlert, Users } from "lucide-react";
import type { CriteriosDeSegmentacao, SimulacaoDePublico } from "@/contratos/apresentacao";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { alterarExclusaoDoPublico, salvarESimularPublico } from "./acoes";

export function DefinicaoPublico({ acaoId, criterios, simulacao, aoSimular, aoAlterarFiltros, aoContinuar }: { acaoId: string; criterios: CriteriosDeSegmentacao; simulacao: SimulacaoDePublico | null; aoSimular: (simulacao: SimulacaoDePublico) => void; aoAlterarFiltros: () => void; aoContinuar?: () => void }) {
  const [mensagem, setMensagem] = useState<string | null>(null); const [pendente, iniciarTransicao] = useTransition();
  function enviar(formData: FormData) { setMensagem(null); iniciarTransicao(async () => { const resultado = await salvarESimularPublico({ acaoId, tipoCliente: String(formData.get("tipoCliente") ?? ""), cidades: String(formData.get("cidades") ?? ""), bairros: String(formData.get("bairros") ?? ""), cadastradoApartirDe: String(formData.get("cadastradoApartirDe") ?? ""), confirmarBaseCompleta: formData.get("confirmarBaseCompleta") === "on" }); if (resultado.sucesso) aoSimular(resultado.simulacao); else setMensagem(resultado.mensagem); }); }
  function alterarExclusao(clienteId: string, excluir: boolean) { setMensagem(null); iniciarTransicao(async () => { const resultado = await alterarExclusaoDoPublico({ acaoId, clienteId, excluir }); if (resultado.sucesso) aoSimular(resultado.simulacao); else setMensagem(resultado.mensagem); }); }
  const elegiveis = simulacao?.clientes.filter((cliente) => cliente.elegivel) ?? [];
  const excluidosManualmente = simulacao?.clientes.filter((cliente) => cliente.motivoExclusao === "ExcluidoManualmente") ?? [];
  return <Card className="mt-6"><CardHeader><CardTitle>1. Escolha quem receberá a mensagem</CardTitle><CardDescription>Preencha somente os filtros que precisar e clique em “Ver clientes”.</CardDescription></CardHeader><CardContent className="space-y-6">
    <form action={enviar} onChange={aoAlterarFiltros} className="grid gap-4 rounded-xl bg-secondary/55 p-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="tipoCliente">Tipo de cliente</Label><Input id="tipoCliente" name="tipoCliente" defaultValue={criterios.tipoCliente ?? ""} placeholder="Ex.: Pessoa física" /></div><div className="space-y-2"><Label htmlFor="cadastradoApartirDe">Cadastrado a partir de</Label><Input id="cadastradoApartirDe" name="cadastradoApartirDe" type="date" defaultValue={criterios.cadastradoApartirDe?.slice(0, 10) ?? ""} /></div><div className="space-y-2"><Label htmlFor="cidades">Cidade</Label><Input id="cidades" name="cidades" defaultValue={criterios.cidades?.join(", ") ?? ""} placeholder="Ex.: Praia Grande" /></div><div className="space-y-2"><Label htmlFor="bairros">Bairro</Label><Input id="bairros" name="bairros" defaultValue={criterios.bairros?.join(", ") ?? ""} placeholder="Ex.: Boqueirão" /></div><label className="flex min-h-11 items-start gap-3 text-sm sm:col-span-2"><input name="confirmarBaseCompleta" type="checkbox" className="mt-0.5 size-5 accent-primary" /><span>Usar todos os clientes quando nenhum filtro estiver preenchido.</span></label>{mensagem && <Alert variant="destructive" className="sm:col-span-2"><AlertTitle>Não foi possível buscar os clientes</AlertTitle><AlertDescription>{mensagem}</AlertDescription></Alert>}<div className="sm:col-span-2"><Button type="submit" disabled={pendente}>{pendente ? "Buscando clientes..." : "Ver clientes"}</Button></div></form>
    {!simulacao && <Alert><Users /><AlertTitle>Primeiro, escolha o público</AlertTitle><AlertDescription>O sistema mostrará apenas quantos clientes realmente podem receber a mensagem.</AlertDescription></Alert>}
    {simulacao && <section aria-live="polite" className="space-y-4">{simulacao.quantidadeElegivel === 0 ? <Alert variant="destructive"><CircleAlert /><AlertTitle>Nenhum cliente pode receber esta mensagem</AlertTitle><AlertDescription>Encontramos {simulacao.quantidadeEncontrada} clientes, mas nenhum possui todos os requisitos para receber WhatsApp. Tente outro filtro ou verifique as permissões dos clientes.</AlertDescription></Alert> : <><div className="rounded-xl border border-primary/25 bg-primary/5 p-5"><p className="text-sm text-muted-foreground">Público pronto</p><p className="mt-1 text-3xl font-bold tabular-nums text-[var(--marca-azul-profundo)]">{simulacao.quantidadeElegivel}</p><p className="text-sm">{simulacao.quantidadeElegivel === 1 ? "cliente pode receber a mensagem" : "clientes podem receber a mensagem"}</p></div>{elegiveis.length > 0 && <details className="rounded-xl border bg-card"><summary className="cursor-pointer px-4 py-3 text-sm font-medium">Conferir alguns clientes</summary><div className="overflow-x-auto border-t"><Table><TableHeader><TableRow><TableHead>Cliente</TableHead><TableHead>WhatsApp</TableHead><TableHead className="text-right">Retirar</TableHead></TableRow></TableHeader><TableBody>{elegiveis.map((cliente) => <TableRow key={cliente.clienteId}><TableCell className="font-medium">{cliente.nome}</TableCell><TableCell>{cliente.whatsapp ?? "Não informado"}</TableCell><TableCell className="text-right"><Button type="button" size="sm" variant="outline" disabled={pendente} onClick={() => alterarExclusao(cliente.clienteId, true)}>Não enviar</Button></TableCell></TableRow>)}</TableBody></Table></div></details>}<div className="flex justify-end"><Button type="button" onClick={aoContinuar}>Continuar para a mensagem<ArrowRight /></Button></div></>}{excluidosManualmente.length > 0 && <details className="rounded-xl border bg-card"><summary className="cursor-pointer px-4 py-3 text-sm font-medium">Clientes retirados manualmente ({excluidosManualmente.length})</summary><div className="space-y-2 border-t p-3">{excluidosManualmente.map((cliente) => <div key={cliente.clienteId} className="flex items-center justify-between gap-3"><span className="text-sm">{cliente.nome}</span><Button type="button" size="sm" variant="outline" disabled={pendente} onClick={() => alterarExclusao(cliente.clienteId, false)}>Colocar novamente</Button></div>)}</div></details>}</section>}
  </CardContent></Card>;
}
