"use client";

import { useState, useTransition } from "react";
import type { CriteriosDeSegmentacao, SimulacaoDePublico } from "@/contratos/apresentacao";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { salvarESimularPublico } from "./acoes";

const motivos = { ClienteInativo: "Cliente inativo", ContatoInvalido: "Contato inválido", SemPermissao: "Sem permissão", ContatoDuplicado: "Contato duplicado" };
export function DefinicaoPublico({ acaoId, criterios }: { acaoId: string; criterios: CriteriosDeSegmentacao }) {
  const [simulacao, setSimulacao] = useState<SimulacaoDePublico | null>(null); const [mensagem, setMensagem] = useState<string | null>(null); const [pendente, iniciarTransicao] = useTransition();
  function enviar(formData: FormData) { setMensagem(null); iniciarTransicao(async () => { const resultado = await salvarESimularPublico({ acaoId, tipoCliente: String(formData.get("tipoCliente") ?? ""), cidades: String(formData.get("cidades") ?? ""), bairros: String(formData.get("bairros") ?? ""), cadastradoApartirDe: String(formData.get("cadastradoApartirDe") ?? ""), confirmarBaseCompleta: formData.get("confirmarBaseCompleta") === "on" }); if (resultado.sucesso) setSimulacao(resultado.simulacao); else setMensagem(resultado.mensagem); }); }
  return <Card className="mt-6"><CardHeader><CardTitle>Definição do público</CardTitle><CardDescription>Filtre a base e confira uma prévia dos clientes antes de preparar a ação.</CardDescription></CardHeader><CardContent className="space-y-6">
    <form action={enviar} className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="tipoCliente">Tipo de cliente</Label><Input id="tipoCliente" name="tipoCliente" defaultValue={criterios.tipoCliente ?? ""} placeholder="Ex.: Pessoa física" /></div><div className="space-y-2"><Label htmlFor="cadastradoApartirDe">Cadastrado a partir de</Label><Input id="cadastradoApartirDe" name="cadastradoApartirDe" type="date" defaultValue={criterios.cadastradoApartirDe?.slice(0, 10) ?? ""} /></div><div className="space-y-2"><Label htmlFor="cidades">Cidades</Label><Input id="cidades" name="cidades" defaultValue={criterios.cidades?.join(", ") ?? ""} placeholder="Separe por vírgulas" /></div><div className="space-y-2"><Label htmlFor="bairros">Bairros</Label><Input id="bairros" name="bairros" defaultValue={criterios.bairros?.join(", ") ?? ""} placeholder="Separe por vírgulas" /></div><label className="flex items-start gap-3 text-sm sm:col-span-2"><input name="confirmarBaseCompleta" type="checkbox" className="mt-0.5 size-4 accent-primary" /><span>Confirmo que, sem filtros preenchidos, a simulação deve considerar toda a base de clientes.</span></label>{mensagem && <Alert variant="destructive" className="sm:col-span-2"><AlertTitle>Não foi possível simular</AlertTitle><AlertDescription>{mensagem}</AlertDescription></Alert>}<div className="sm:col-span-2"><Button type="submit" disabled={pendente}>{pendente ? "Salvando e simulando..." : "Salvar filtros e simular público"}</Button></div></form>
    {simulacao && <section aria-live="polite" className="space-y-4"><div className="flex flex-wrap gap-2"><Badge variant="secondary">{simulacao.quantidadeEncontrada} encontrados</Badge><Badge>{simulacao.quantidadeElegivel} elegíveis</Badge><Badge variant="outline">{simulacao.quantidadeEncontrada - simulacao.quantidadeElegivel} excluídos</Badge></div>{simulacao.clientes.length === 0 ? <p className="text-sm text-muted-foreground">Nenhum cliente corresponde aos filtros atuais.</p> : <div className="overflow-x-auto rounded-md border"><Table><TableHeader><TableRow><TableHead>Cliente</TableHead><TableHead>WhatsApp</TableHead><TableHead>Situação</TableHead></TableRow></TableHeader><TableBody>{simulacao.clientes.map((cliente) => <TableRow key={cliente.clienteId}><TableCell className="font-medium">{cliente.nome}</TableCell><TableCell>{cliente.whatsapp ?? "Não informado"}</TableCell><TableCell>{cliente.elegivel ? <Badge>Elegível</Badge> : <Badge variant="secondary">{cliente.motivoExclusao ? motivos[cliente.motivoExclusao] : "Excluído"}</Badge>}</TableCell></TableRow>)}</TableBody></Table></div>}</section>}
  </CardContent></Card>;
}
