"use client";

import { useState, useTransition } from "react";
import { ArrowRight, CircleAlert, Users } from "lucide-react";
import type { CriteriosDeSegmentacao, SimulacaoDePublico } from "@/contratos/apresentacao";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { bairrosAtendidosPorCidade, cidadesAtendidas, type CidadeAtendida } from "@/conteudo/area-atendimento-lavamais";
import { alterarExclusaoDoPublico, salvarESimularPublico } from "./acoes";

export function DefinicaoPublico({ acaoId, criterios, simulacao, aoSimular, aoAlterarFiltros, aoContinuar }: { acaoId: string; criterios: CriteriosDeSegmentacao; simulacao: SimulacaoDePublico | null; aoSimular: (simulacao: SimulacaoDePublico) => void; aoAlterarFiltros: () => void; aoContinuar?: () => void }) {
  const [mensagem, setMensagem] = useState<string | null>(null); const [pendente, iniciarTransicao] = useTransition();
  const cidadeInicial = criterios.cidades?.[0];
  const [cidade, setCidade] = useState<CidadeAtendida | "">(cidadesAtendidas.includes(cidadeInicial as CidadeAtendida) ? cidadeInicial as CidadeAtendida : "");
  const [bairro, setBairro] = useState(criterios.bairros?.length === 1 ? criterios.bairros[0] : "todos");
  const bairrosDisponiveis = cidade ? bairrosAtendidosPorCidade[cidade] : [];
  function alterarCidade(valor: string) { setCidade(valor as CidadeAtendida); setBairro("todos"); aoAlterarFiltros(); }
  function enviar() { if (!cidade) return; setMensagem(null); const bairros = bairro === "todos" ? bairrosDisponiveis.join(",") : bairro; iniciarTransicao(async () => { const resultado = await salvarESimularPublico({ acaoId, cidades: cidade, bairros }); if (resultado.sucesso) aoSimular(resultado.simulacao); else setMensagem(resultado.mensagem); }); }
  function alterarExclusao(clienteId: string, excluir: boolean) { setMensagem(null); iniciarTransicao(async () => { const resultado = await alterarExclusaoDoPublico({ acaoId, clienteId, excluir }); if (resultado.sucesso) aoSimular(resultado.simulacao); else setMensagem(resultado.mensagem); }); }
  const elegiveis = simulacao?.clientes.filter((cliente) => cliente.elegivel) ?? [];
  const excluidosManualmente = simulacao?.clientes.filter((cliente) => cliente.motivoExclusao === "ExcluidoManualmente") ?? [];
  return <Card className="mt-6"><CardHeader><CardTitle>1. Escolha quem receberá a mensagem</CardTitle><CardDescription>Selecione a cidade e o bairro atendidos pela LavaMais.</CardDescription></CardHeader><CardContent className="space-y-6">
    <form onSubmit={(evento) => { evento.preventDefault(); enviar(); }} className="grid gap-4 rounded-xl bg-secondary/55 p-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="cidades">Cidade</Label><Select value={cidade} onValueChange={alterarCidade}><SelectTrigger id="cidades"><SelectValue placeholder="Selecione a cidade" /></SelectTrigger><SelectContent>{cidadesAtendidas.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="bairros">Bairro</Label><Select value={bairro} onValueChange={(valor) => { setBairro(valor); aoAlterarFiltros(); }} disabled={!cidade}><SelectTrigger id="bairros"><SelectValue placeholder="Selecione primeiro a cidade" /></SelectTrigger><SelectContent><SelectItem value="todos">Todos os bairros atendidos</SelectItem>{bairrosDisponiveis.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><p className="text-xs text-muted-foreground sm:col-span-2">A lista considera a área inicial de atendimento da LavaMais, próxima ao Canto do Forte.</p>{mensagem && <Alert variant="destructive" className="sm:col-span-2"><AlertTitle>Não foi possível buscar os clientes</AlertTitle><AlertDescription>{mensagem}</AlertDescription></Alert>}<div className="sm:col-span-2"><Button type="submit" disabled={pendente || !cidade}>{pendente ? "Buscando clientes..." : "Ver clientes"}</Button></div></form>
    {!simulacao && <Alert><Users /><AlertTitle>Primeiro, escolha o público</AlertTitle><AlertDescription>O sistema mostrará apenas quantos clientes realmente podem receber a mensagem.</AlertDescription></Alert>}
    {simulacao && <section aria-live="polite" className="space-y-4">{simulacao.quantidadeElegivel === 0 ? <Alert variant="destructive"><CircleAlert /><AlertTitle>Nenhum cliente pode receber esta mensagem</AlertTitle><AlertDescription>Encontramos {simulacao.quantidadeEncontrada} clientes, mas nenhum possui todos os requisitos para receber WhatsApp. Tente outro bairro ou verifique as permissões dos clientes.</AlertDescription></Alert> : <><div className="rounded-xl border border-primary/25 bg-primary/5 p-5"><p className="text-sm font-medium text-[var(--marca-azul-profundo)]">Público pronto — nenhuma mensagem foi enviada</p><p className="mt-2 text-3xl font-bold tabular-nums text-[var(--marca-azul-profundo)]">{simulacao.quantidadeElegivel}</p><p className="text-sm">{simulacao.quantidadeElegivel === 1 ? "cliente pode receber WhatsApp" : "clientes podem receber WhatsApp"} em {bairro === "todos" ? "todos os bairros atendidos" : bairro}, {cidade}.</p><div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-card px-3 py-1.5 ring-1 ring-border">{simulacao.quantidadeEncontrada} encontrados</span><span className="rounded-full bg-card px-3 py-1.5 ring-1 ring-border">{simulacao.quantidadeEncontrada - simulacao.quantidadeElegivel} não elegíveis</span></div></div>{elegiveis.length > 0 && <details className="rounded-xl border bg-card"><summary className="cursor-pointer px-4 py-3 text-sm font-medium">Conferir alguns clientes</summary><div className="overflow-x-auto border-t"><Table><TableHeader><TableRow><TableHead>Cliente</TableHead><TableHead>WhatsApp</TableHead><TableHead className="text-right">Retirar</TableHead></TableRow></TableHeader><TableBody>{elegiveis.map((cliente) => <TableRow key={cliente.clienteId}><TableCell className="font-medium">{cliente.nome}</TableCell><TableCell>{cliente.whatsapp ?? "Não informado"}</TableCell><TableCell className="text-right"><Button type="button" size="sm" variant="outline" disabled={pendente} onClick={() => alterarExclusao(cliente.clienteId, true)}>Não enviar</Button></TableCell></TableRow>)}</TableBody></Table></div></details>}<div className="flex justify-end"><Button type="button" onClick={aoContinuar}>Continuar para a mensagem<ArrowRight /></Button></div></>}{excluidosManualmente.length > 0 && <details className="rounded-xl border bg-card"><summary className="cursor-pointer px-4 py-3 text-sm font-medium">Clientes retirados manualmente ({excluidosManualmente.length})</summary><div className="space-y-2 border-t p-3">{excluidosManualmente.map((cliente) => <div key={cliente.clienteId} className="flex items-center justify-between gap-3"><span className="text-sm">{cliente.nome}</span><Button type="button" size="sm" variant="outline" disabled={pendente} onClick={() => alterarExclusao(cliente.clienteId, false)}>Colocar novamente</Button></div>)}</div></details>}</section>}
  </CardContent></Card>;
}
