// <auto-generated />
using System;
using LavaMais.Crm.Modulos.Auditoria.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LavaMais.Crm.Modulos.Auditoria.Infraestrutura.Migrations
{
    [DbContext(typeof(ContextoDeAuditoria))]
    partial class ContextoDeAuditoriaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auditoria")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LavaMais.Crm.Modulos.Auditoria.Dominio.RegistroDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DadosJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_json");

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recurso");

                    b.Property<Guid>("RecursoId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurso_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.Property<string>("UsuarioIdentidadeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario_identidade_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Recurso", "RecursoId");

                    b.ToTable("registros_de_auditoria", "auditoria");
                });
#pragma warning restore 612, 618
        }
    }
}
