<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <ProjectReference Include="../BlocosDeConstrucao/LavaMais.Crm.BlocosDeConstrucao.csproj" />
    <ProjectReference Include="../Modulos/Autorizacao/LavaMais.Crm.Modulos.Autorizacao.csproj" />
  </ItemGroup>
</Project>
