// <auto-generated />
using System;
using LavaMais.Crm.Modulos.Clientes.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LavaMais.Crm.Modulos.Clientes.Infraestrutura.Migrations
{
    [DbContext(typeof(ContextoDeClientes))]
    [Migration("20260815142303_CriarClientesInicial")]
    partial class CriarClientesInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("clientes")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LavaMais.Crm.Modulos.Clientes.Dominio.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("situacao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("clientes", "clientes");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.Clientes.Dominio.ClienteEtiqueta", b =>
                {
                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<Guid>("EtiquetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etiqueta_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("ClienteId", "EtiquetaId");

                    b.HasIndex("EtiquetaId");

                    b.ToTable("clientes_etiquetas", "clientes");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.Clientes.Dominio.ContatoDoCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("situacao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("valor");

                    b.Property<string>("ValorNormalizado")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("valor_normalizado");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TenantId", "ValorNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ux_whatsapp_ativo_por_tenant")
                        .HasFilter("tipo = 'Whatsapp' AND situacao = 'Ativo'");

                    b.ToTable("contatos_do_cliente", "clientes");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.Clientes.Dominio.EnderecoDoCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("enderecos_do_cliente", "clientes");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.Clientes.Dominio.Etiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome_normalizado");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NomeNormalizado")
                        .IsUnique();

                    b.ToTable("etiquetas", "clientes");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.Clientes.Dominio.PermissaoDeComunicacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<string>("Finalidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("finalidade");

                    b.Property<bool>("Permitida")
                        .HasColumnType("boolean")
                        .HasColumnName("permitida");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TenantId", "ClienteId", "Canal", "Finalidade")
                        .IsUnique();

                    b.ToTable("permissoes_de_comunicacao", "clientes");
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.Clientes.Dominio.ClienteEtiqueta", b =>
                {
                    b.HasOne("LavaMais.Crm.Modulos.Clientes.Dominio.Cliente", null)
                        .WithMany("Etiquetas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LavaMais.Crm.Modulos.Clientes.Dominio.Etiqueta", null)
                        .WithMany()
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.Clientes.Dominio.ContatoDoCliente", b =>
                {
                    b.HasOne("LavaMais.Crm.Modulos.Clientes.Dominio.Cliente", null)
                        .WithMany("Contatos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.Clientes.Dominio.EnderecoDoCliente", b =>
                {
                    b.HasOne("LavaMais.Crm.Modulos.Clientes.Dominio.Cliente", null)
                        .WithOne("Endereco")
                        .HasForeignKey("LavaMais.Crm.Modulos.Clientes.Dominio.EnderecoDoCliente", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.Clientes.Dominio.PermissaoDeComunicacao", b =>
                {
                    b.HasOne("LavaMais.Crm.Modulos.Clientes.Dominio.Cliente", null)
                        .WithMany("Permissoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LavaMais.Crm.Modulos.Clientes.Dominio.Cliente", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Endereco");

                    b.Navigation("Etiquetas");

                    b.Navigation("Permissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
