<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <ProjectReference Include="../BlocosDeConstrucao/LavaMais.Crm.BlocosDeConstrucao.csproj" />
    <ProjectReference Include="../Modulos/AcoesComerciais/LavaMais.Crm.Modulos.AcoesComerciais.csproj" />
    <ProjectReference Include="../Modulos/Auditoria/LavaMais.Crm.Modulos.Auditoria.csproj" />
    <ProjectReference Include="../Modulos/Autorizacao/LavaMais.Crm.Modulos.Autorizacao.csproj" />
    <ProjectReference Include="../Modulos/Catalogo/LavaMais.Crm.Modulos.Catalogo.csproj" />
    <ProjectReference Include="../Modulos/Clientes/LavaMais.Crm.Modulos.Clientes.csproj" />
    <ProjectReference Include="../Modulos/Importacoes/LavaMais.Crm.Modulos.Importacoes.csproj" />
    <ProjectReference Include="../Modulos/Integracoes/LavaMais.Crm.Modulos.Integracoes.csproj" />
    <ProjectReference Include="../Modulos/ModelosDeMensagem/LavaMais.Crm.Modulos.ModelosDeMensagem.csproj" />
    <ProjectReference Include="../Modulos/Segmentacao/LavaMais.Crm.Modulos.Segmentacao.csproj" />
  </ItemGroup>
</Project>
